{{- if .Values.istio.enable -}}
{{- $name := .Values.fullnameOverride }}
{{- $url := printf "%s.%s.svc.cluster.local" $name .Release.Namespace }}
{{- $port := .Values.service.ports.http }}

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: "{{ $name }}-virtual-service"
spec:
  hosts:
    - {{ $url }}
  http:
    - match:
        {{- toYaml .Values.istio.virtualService.http.match | nindent 6 }}
      rewrite:
        uri: {{ .Values.istio.virtualService.http.rewrite.uri }}
      route:
        {{- range $k, $v := .Values.istio.subsets }}
        - destination:
            host: {{ $url }}
            subset: {{ regexReplaceAll "\\.+" $v.version "-" }}
            port:
              number: {{ $port }}
          weight: {{ $v.weight }}
          {{- if $v.mirror }}
          mirror:
            host: {{ $url }}
            subset: {{ regexReplaceAll "\\.+" $v.mirror.version "-" }}
            mirrorPercentage:
              value: {{ $v.mirror.mirrorPercentage }}
          {{- end }}
        {{- end }}
{{- end }}