{{- if .Values.istio.enable -}}
{{- $name := .Values.fullnameOverride }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: "{{ $name }}-destination-rule"
spec:
  host: {{ $name }}.{{ .Release.Namespace }}.svc.cluster.local
  subsets:
    {{- range $k, $v := .Values.istio.subsets }}
    - name: {{ regexReplaceAll "\\.+" $v.version "-" }}
      labels:
        version: {{ $v.version }}
    {{- end }}
{{- end }}